name: hmds_food_order
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DEPENDENCIES YANG BENAR
  http: ^1.2.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.8.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_hmds.png
    - assets/images/vegetarian/alamihemat.jpeg
    - assets/images/vegetarian/alamiberkah.jpeg
    - assets/images/vegetarian/alamimini.jpeg
    - assets/images/vegetarian/miealami.jpeg
    - assets/images/vegetarian/miesalad.jpeg
    - assets/images/vegetarian/naskunbahagia.jpeg
    - assets/images/vegetarian/naskunberlimpah.jpeg
    - assets/images/vegetarian/naskunhemat.jpeg
    - assets/images/vegetarian/naskunmini.jpeg

    - assets/images/non_vegetarian/asam-manis.jpeg
    - assets/images/non_vegetarian/bbq.jpeg
    - assets/images/non_vegetarian/bulgogi.jpeg
    - assets/images/non_vegetarian/mie_sinyemek.jpeg
    - assets/images/non_vegetarian/nasigoreng.jpeg
    - assets/images/non_vegetarian/silpasta.jpeg
    - assets/images/non_vegetarian/teriyaki.jpeg

    - assets/images/minuman/air_mineral.jpeg
    - assets/images/minuman/americano.jpeg
    - assets/images/minuman/es_batu.jpeg
    - assets/images/minuman/kopi_susu.jpeg
    - assets/images/minuman/liang teh.jpeg
    - assets/images/minuman/lo-han-guo.jpeg
    - assets/images/minuman/lychee yakult.jpeg
    - assets/images/minuman/matcha-latte.jpeg
    - assets/images/minuman/teh.jpeg
    - assets/images/minuman/teh_manis.jpeg
